spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/provider?useTimezone=true&serverTimezone=UTC"
        username: "root"
        password: "root"
    jpa:
        hibernate:
            ddl-auto: "update"
